MovieBS/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.static import serve
from film import views
from MovieBS import settings
from stark.service import v1

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^stark/', v1.site.urls),
    url(r'^login/', views.login),
    url(r'^logout', views.logout),
    url(r'^reg/', views.reg),
    url(r'^get_validCode_img/', views.get_validCode_img),
    url(r'^index/', views.index),
    url(r'^film/(?P<nid>\d+)/detail/', views.Detail),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

film/forms.py
from django import forms
from django.forms import widgets,ValidationError
from .models import *
from django.forms import ModelForm

# class LoginForm(forms.Form):
#     username = forms.CharField(label='username',max_length=100)
#     password = forms.CharField(label='password',max_length=100)
#
#     def clean_username(self):
#         if len(self.cleaned_data.get('username'))>5:
#             print(self.cleaned_data.get('password'))
#             return self.cleaned_data.get('username')
#         else:
#             raise ValidationError("用户名长度小于5")
#     def clean_password(self):
#         pass
#
#     def clean(self):
#         if  self.cleaned_data["password"] == self.cleaned_data['repeat_password']:
#             return  self.cleaned_data


class RegForm(forms.Form):

    username = forms.CharField(
        max_length=18,min_length=3,
        error_messages={"required":"用户名不能为空","min_length":"用户名少于3个字符","max_length":"用户名大于18个字符"},
        widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"username"}))

    password = forms.CharField(
        max_length=18,min_length=3,
        error_messages={"required": "密码不能为空", "min_length": "密码少于3个字符", "max_length": "用户名大于18个字符"},
        widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"password"}))

    repeat_pwd = forms.CharField(
        error_messages={"required": "确认密码不能为空"},
        widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"repeat_pwd"}))

    phone = forms.CharField(
        error_messages={"required": "手机号不能为空"},
        widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"手机号"}))

    def clean_username(self):
        ret = UserInfo.objects.filter(username=self.cleaned_data.get("username"))
        if not ret:
            return self.cleaned_data
        else:
            raise  ValidationError("用户名已注册")

    def clean_repeat_pwd(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("repeat_pwd"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")

    def clean_phone(self):
        if len(self.cleaned_data.get("phone")) == 11:
            return self.cleaned_data
        else:
            raise ValidationError("手机号格式不对")

    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request=request

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Base</title>
    {% endblock %}

    <style>
                * {
            margin: 0;
            padding: 0;
        }

        #mar {
            z-index: 1111;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            margin-bottom: 0;
        }
    </style>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/dist/js/bootstrap.min.js"></script>
    {% block CSS %}
    {% endblock %}
    {% block JS %}
    {% endblock %}
</head>
<body>
<!-- 导航条 -->
<nav class="navbar navbar-default" id="mar">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/index/">首页</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="">频道<span class="sr-only">(current)</span></a></li>
                <li><a href="#">活动</a></li>
                <li><a href="/stark/film/userinfo/">管理</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="input-group">
                    <input type="text" class="form-control " placeholder="Search">
                    <span class="input-group-btn">
                        <button class="btn btn-default btn-sm" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>

            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="/logout/">注销</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人信息 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load my_tags  %}

{% block title %}
    <title>主页</title>
{% endblock %}

{% block CSS %}
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/vs.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/screen.min.css">
    <link rel="stylesheet" href="/static/css/ysemm.css">

    <style>
        .carousel-inner .item .img {
            width: 100%;
            height: 400px;
        }

        .martop {
            margin-top: 35px;
            width: 100%;
        }

        .index-main {
            background-color: #fff;
            padding: 20px;
            height: auto;
        }

        .index-list {
            margin-top: 40px;
            background-color: #fff;
            list-style: none;
        }

        .index-list li {
            width: 800px;
            height: 200px;
            margin-top: 40px;
        }

        .index-img {
            width: 300px;
            height: 200px;
            float: left;
            position: relative;
        }

        .index-list .img {
            width: 300px;
            height: 200px;
        }

        .film-time {
            position: absolute;
            right: 2px;
            bottom: 2px;
            color: #F1F1F1;
        }

        .index-text {
            width: 420px;
            height: 200px;
            position: relative;
            /*background-color: red;*/
            float: left;
            margin-left: 20px;
        }

        .index-text h1 {
            font-size: 20px;
            color: #333;
            font-weight: bold;
            line-height: 34px;
        }

        .index-text h1 a {
            color: #333;
        }

        .index-con {
            color: #999;
            font-size: 12px;
            height: 24px;
            line-height: 24px;
            float: left;
        }

        .user {
            color: #666;
            font-weight: bold;
        }

        .rating {
            display: inline-block;
        }

        .rating-holder {
            display: inline-block;
            width: 90px;
            height: 14px;
            background: url("/static/img/star-no.png");
            overflow: hidden;
        }

        .rating-span {
            height: 14px;
            display: inline-block;
            background: url("/static/img/star-yes.png");
            z-index: 1;
        }

        .rating-score {
            display: inline-block;
            color: #F7B42C;
            font-size: 14px;
        }

        .index-intro {
            float: left;
            clear: both;
            width: 100%;
            font-size: 16px;
            line-height: 26px;
        }

        .index-intro a {
            color: #747f8c;
        }

        .index-like {
            position: absolute;
            width: 100%;
            bottom: 0;
            height: 24px;
            line-height: 24px;
            font-size: 12px;
            color: #999;
        }

        .post-ope {
            float: right;
        }

        .post-ope a {
            font-size: 12px;
            color: #999;
        }

        .post-comment {
            display: inline-block;
            height: 24px;
            line-height: 24px;
            background: url("/static/img/comment.png") no-repeat 0 0;
            padding: 0 10px 0 24px;
        }

        .post-like {
            /*display: inline-block;*/
            background: url("/static/img/like.png") no-repeat 0 0;
            padding: 0 10px 7px 24px;
        }

        .post-share-btn {
            background: url("/static/img/share.png") no-repeat 0 0;
            padding: 0 2px 7px 24px;
        }


    </style>
{% endblock %}

{% block JS %}
{% endblock %}

{% block body %}
    <!-- 图片轮播 -->
    <div id="carousel-example-generic" class="center-block carousel slide martop" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="/static/img/TurnPic/video1.jpg" class="img" alt="pic1">
                <div class="carousel-caption">
                    左耳
                </div>
            </div>
            <div class="item">
                <img src="/static/img/TurnPic/video2.jpg" class="img" alt="pic4">
                <div class="carousel-caption">
                    微微一笑很倾城
                </div>
            </div>
            <div class="item">
                <img src="/static/img/TurnPic/video3.jpg" class="img" alt="pic3">
                <div class="carousel-caption">
                    忘了去懂你
                </div>
            </div>
            <div class="item">
                <img src="/static/img/TurnPic/video4.jpg" class="img" alt="pic1">
                <div class="carousel-caption">
                    花非花雾非雾电视剧
                </div>
            </div>
            <div class="item">
                <img src="/static/img/TurnPic/video5.jpg" class="img" alt="pic1">
                <div class="carousel-caption">
                    真正男子汉第二季空军篇
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!--main-->
    <section class="content-wrap martop">
        <div class="container">
            <div class="row">
                <!--left电影列表-->
                <main class="col-md-8 index-main">
                    <ul class="index-list">
                        {% for movie in film_objs %}
                        <li>
                            <div class="index-img">
                                <a href="">
                                    <img src="/media/upload/{{ movie.img }}" class="img">
                                    <span class="film-time">{{ movie.period }} 分钟</span>
                                </a>
                            </div>
                            <div class="index-text">
                                <h1><a href="/film/{{ movie.pk }}/detail/" title="{{ movie.name }}">{{ movie.name }}</a></h1>
                                <div class="index-con">
                                    <span>影片导演：</span>
                                    <a href="" class="user" title="{% get_direction movie %}">{% get_direction movie %}<img src="/static/img/plus-v-p-12.png"></a>
                                    <div class="rating">
                                        <div class="rating-holder">
                                            <span class="rating-span" style="width:66px;"></span>
                                        </div>
                                    </div>
                                    <span class="rating-score">{{ movie.score }}</span>
                                </div>
                                <div class="index-intro">
                                    <a href="">{{ movie.info }}</a>
                                </div>
                                <div class="index-like">
                                    <span>{% get_movietype movie  %}</span>
                                    <div class="post-ope">
                                        <span class="post-comment">{{ movie.comment_num }}</span>
                                        <span class="post-like">{{ movie.like_num }}</span>
                                        <a href="" class="post-share-btn">{{ movie.share_num }}</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                        {% endfor %}

                    </ul>


                    <nav class="pagination" role="navigation">
                        <span class="page-number">第 1 页 / 共 5 页</span>
                        <a class="older-posts" href="#"> <i class="fa ">1</i> </a>
                        <a class="older-posts" href="#"> <i class="fa ">2</i> </a>
                        <a class="older-posts" href="#"> <i class="fa ">3</i> </a>
                        <a class="older-posts" href="#"> <i class="fa ">4</i> </a>
                        <a class="older-posts" href="#"> <i class="fa ">5</i> </a>
                    </nav>
                </main>
                <!--right标题栏-->
                <aside class="col-md-4 sidebar">
                    <div class="widget">
                        <h4 class="title">社区</h4>
                        <div class="content community">
                            <p>QQ群：462694081</p>
                            <p><a href="#" title="电影社区"><i class="fa fa-comments"></i> 问答社区</a></p></div>
                    </div>

                    <div class="widget"><h4 class="title">热门频道</h4>
                        <a href="#" class="btn btn-default btn-block">电影自习室</a>
                        <a href="#" class="btn btn-default btn-block">创意</a>
                        <a href="#" class="btn btn-default btn-block">旅行</a>
                        <a href="#" class="btn btn-default btn-block">科幻</a>
                        <a href="#" class="btn btn-default btn-block">运动</a>
                    </div>

                    <div class="widget">
                        <h4 class="title">热门活动</h4>
                        <a href="#" class="btn btn-block ">
                            <img src="/static/img/activity/r_item1.jpg" alt="..." class="img-thumbnail">
                        </a>
                        <a href="#" class="btn btn-block">
                            <img src="/static/img/activity/r_item2.jpg" alt="..." class="img-thumbnail">
                        </a>
                        <a href="#" class="btn btn-block">
                            <img src="/static/img/activity/r_item3.jpg" alt="..." class="img-thumbnail">
                        </a>
                        <a href="#" class="btn btn-block">
                            <img src="/static/img/activity/r_item4.png" alt="..." class="img-thumbnail">
                        </a>
                        <a href="#" class="btn btn-block">
                            <img src="/static/img/activity/r_item5.jpg" alt="..." class="img-thumbnail">
                        </a>
                        <a href="#" class="btn btn-block">
                            <img src="/static/img/activity/r_item6.jpg" alt="..." class="img-thumbnail">
                        </a>
                    </div>
                </aside>
            </div>
        </div>
    </section>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>
    <script src="/static/js/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/login.css">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" placeholder="username">
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" placeholder="password">
                </div>

                <div class="row validCode">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="validCode">验证码</label>
                            <input type="text" class="form-control validCode_text" id="validCode"
                                   placeholder="validCode">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <img class="validCode_img" src="/get_validCode_img/" alt="" width="200px" height="50px">
                    </div>
                </div>


                <input type="button" value="登录" class="btn btn-primary" id="subBtn">
                <a href="/reg/"><input type="button" class="btn btn-primary col-md-offset-1" value=注册></a><span class="error"></span>

                <div id="popup-captcha"></div>
            </form>
        </div>
    </div>
</div>


<script>
    $("#subBtn").click(function () {
        $.ajax({
            url: "/login/",
            type: "POST",
            data: {
                "username": $("#username").val(),
                "password": $("#password").val(),
                "validCode": $("#validCode").val(),
                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val()
            },
            success: function (data) {
                console.log(data);
                if (data["is_login"]) {
                    location.href = "/index/"
                } else {
                    $(".error").html(data["error_msg"]).css("color", "red")
                }
            }
        })
    })
</script>



</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>
    <script src="/static/js/jquery-3.1.1.js"></script>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/reg.css">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <form>
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="username">用户名</label>
                        {{ form_obj.username }}
                          <span></span>
                      </div>
                      <div class="form-group">
                        <label for="password">密码</label>
                        {{ form_obj.password }}
                         <span></span>
                      </div>

                       <div class="form-group">
                        <label for="password">确认密码</label>
                           {{ form_obj.repeat_pwd }}
                           <span></span>

                      </div>

                      <div class="form-group">
                        <label for="phone">手机号</label>
                          {{ form_obj.phone }}
                          <span></span>
                      </div>

                      <div class="form-group avatar">
                        <label for="avatar">头像</label>
                        <img src="/static/img/default.jpg" alt="" id="avatar_img" >
                        <input type="file"  id="avatar_file" >
                      </div>
                    <input type="button" value="submit" class="btn btn-primary" id="subBtn">
                </form>
        </div>
    </div>
</div>

<script>


    $("#avatar_file").change(function () {
       var ele_file = $(this)[0].files[0];
       var reader = new FileReader();
       reader.readAsDataURL(ele_file);
       reader.onload=function () {
           $("#avatar_img")[0].src=this.result;
       }
    });

    $("#subBtn").click(function () {

        var formdata = new FormData();
        formdata.append("username",$("#id_username").val());
        formdata.append("password",$("#id_password").val());
        formdata.append("repeat_pwd",$("#id_repeat_pwd").val());
        formdata.append("phone",$("#id_phone").val());
        if ($("#avatar_file")[0].files[0]){
            formdata.append("head_img",$("#avatar_file")[0].files[0]);
        }


        $.ajax({
            url:"/reg/",
            type:"POST",
            data:formdata,
            contentType:false,
            processData:false,
            headers:{"X-CSRFToken":$("[name='csrfmiddlewaretoken']").val()},
            success:function (data) {
                if (data.user){
                    location.href = "/index/"
                }
                else{
                    $(".has-error").each(function () {
                        $(this).html("")
                    });
                    $.each(data.errorList, function (i, j) {
                            $("#id_" + i).next().html(j[0]).addClass("pull-right has-error").css("color","red");
                        });
                }
            }
        })
    })
</script>
</body>
</html>